source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'VLFramework_Example', :exclusive => true do
  pod "VLFramework", :path => "../"
end

target 'VLFramework_Tests', :exclusive => true do
  pod "VLFramework", :path => "../"

  
end
